### ISSUE TITLE
Create a docker-compose.tpl and gitignore to current docker-compose.yml

### ISSUE THREAD

**Issue by giper45** [cybersecsi/dockerized-android#2]
As the `docker-compose.yml` in the repo is an example and should be changed, it would be useful to have a `docker-compose.tpl` in the repo, tell the user to run `cp docker-compose.tpl docker-compose.yml` and let the user change the real docker-compose.yml. You can add docker-compose.yml in the `.gitignore`

**Comment by daniele-capone** [comment]
Added three possible configurations in the `examples` folder in 8bb102cf7cf5903a466d702d64644a67da9ee0bb
